### ISSUE TITLE
Unable to run Gradle on arm64 platform target

### ISSUE THREAD

**Issue by dzikoysk** [keeganwitt/docker-gradle#196]
Using arm64 image instead of amd64 just kills Gradle process before it even starts to build application:

```
#12 [build 4/4] RUN gradle shadowJar --no-daemon --stacktrace
#12 6.294 
#12 6.297 Welcome to Gradle 7.2!
#12 6.299 
#12 6.301 Here are the highlights of this release:
#12 6.305  - Toolchain support for Scala
#12 6.314  - More cache hits when Java source files have platform-specific line endings
#12 6.321  - More resilient remote HTTP build cache behavior
#12 6.322 
#12 6.324 For more details see https://docs.gradle.org/7.2/release-notes.html
#12 6.324 
#12 7.700 To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
#12 8.481 
#12 8.482 FAILURE: Build failed with an exception.
#12 8.485 
#12 8.486 * What went wrong:
#12 8.514 A problem occurred starting process 'Gradle build daemon'
#12 8.515 
#12 8.515 * Try:
#12 8.515 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#12 8.517 
#12 8.517 * Exception is:
#12 8.517 org.gradle.process.internal.ExecException: A problem occurred starting process 'Gradle build daemon'
#12 8.518 	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
#12 8.518 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
#12 8.518 	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:369)
#12 8.519 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
#12 8.519 	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:38)
#12 8.519 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
#12 8.520 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
#12 8.521 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
#12 8.521 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
#12 8.521 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
#12 8.521 	at java.base/java.lang.Thread.run(Thread.java:831)
#12 8.522 Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/opt/java/openjdk/bin/java'
#12 8.522 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
#12 8.523 	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
#12 8.523 	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
#12 8.523 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
#12 8.524 	... 7 more
#12 8.524 Caused by: java.io.IOException: Cannot run program "/opt/java/openjdk/bin/java" (in directory "/home/gradle/.gradle/daemon/7.2"): error=0, Failed to exec spawn helper: pid: 62, exit value: 1
#12 8.524 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
#12 8.525 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
#12 8.525 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
#12 8.525 	... 10 more
#12 8.526 Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 62, exit value: 1
#12 8.526 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
#12 8.527 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
#12 8.527 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
#12 8.527 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
#12 8.528 	... 12 more
#12 8.528 
#12 8.528 
#12 8.528 * Get more help at https://help.gradle.org
#12 ERROR: process "/bin/sh -c gradle shadowJar --no-daemon --stacktrace" did not complete successfully: exit code: 1
------
 > [build 4/4] RUN gradle shadowJar --no-daemon --stacktrace:
#12 8.525 	... 10 more
#12 8.526 Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 62, exit value: 1
#12 8.526 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
#12 8.527 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
#12 8.527 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
#12 8.527 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
#12 8.528 	... 12 more
#12 8.528 
#12 8.528 
#12 8.528 * Get more help at https://help.gradle.org
------
Dockerfile:5
--------------------
   3 |     COPY --chown=gradle:gradle . /home/gradle/src
   4 |     WORKDIR /home/gradle/src
   5 | >>> RUN gradle shadowJar --no-daemon --stacktrace
   6 |     
   7 |     # Build-time metadata stage
--------------------
error: failed to solve: process "/bin/sh -c gradle shadowJar --no-daemon --stacktrace" did not complete successfully: exit code: 1
```

Tbh I have no idea what might be the reason at this point. Full log: 

* https://github.com/dzikoysk/reposilite/runs/3526091903

It's some kind of a permissions issue maybe 🤔

**Comment by keeganwitt** [comment]
Can you try again? The latest images have a new base image, which might have had an effect.

**Comment by dzikoysk** [comment]
Forget to close this, it's Gradle bug:

* https://github.com/gradle/gradle/issues/18212

**Comment by keeganwitt** [comment]
Thanks for the link!

**Comment by keeganwitt** [comment]
If it doesn't get fixed, possibly we could add `GRADLE_OPTS` as an `ENV` Dockerfile conditionally using `TARGETARCH`.

**Comment by keeganwitt** [comment]
If I work out the right way to do that, would you be able to test it? I don't have any Arm stuff around. I probably should get something running in AWS so I can test these kinds of things...

**Comment by keeganwitt** [comment]
I'm experimenting with that here: https://github.com/keeganwitt/docker-gradle/pull/200.

GRADLE_OPTS got set, but it's still segfaulting. You said that fix worked for you though?

**Comment by dzikoysk** [comment]
Yup, that's my current Dockerfile:

* https://github.com/dzikoysk/reposilite/blob/main/Dockerfile

I wonder if it's not because of missing `--no-daemon` mode.

**Comment by keeganwitt** [comment]
It's actually happening in wget, bizarrely. Not the gradle command.
