### ISSUE TITLE
unable to create docker image with Gradle 4.2.1, gradleSpringBootPluginVersion=2.0.0.RELEASE  AND spring cloudVersion=Finchley.M9

### ISSUE THREAD

**Issue by batarayappa** [keeganwitt/docker-gradle#51]
Hi ,

I'm trying migrate my application from springboot 1.x to springboot 2.0.0.RELEASE  AND spring cloudVersion=Finchley.M9. Docker image is not getting creating with Gradle 4.2.1, gradleSpringBootPluginVersion=2.0.0.RELEASE  AND spring cloudVersion=Finchley.M9.

can you please help to trace this issue? Please find below stack trace 

> applicationname :
Inferred project: parentapplication, version: xxxxx-SNAPSHOT
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_269oudg0suw5gqpkcjl5mme0v.run(/<applicationpath>/build.gradle:158)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Task :applicationname:buildDockerImage
Building image using context '/<local drive path>/<applicationname>/build'.
Using tag '<jenkinspath>' for image.

[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
java.lang.IllegalStateException: InjectionManagerFactory not found.
        at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
        at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
        at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
        at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applicationname:buildDockerImage'.
> InjectionManagerFactory not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by keeganwitt** [comment]
This is an issue with the Spring Boot setup in your project, not Gradle or this Docker image.  I couldn't even begin to guess what's going on without more information about your environment, sorry.

**Comment by keeganwitt** [comment]
Are you using this Gradle Docker plugin?  I saw there was a similar issue reported last year over there https://github.com/bmuschko/gradle-docker-plugin/issues/467

**Comment by batarayappa** [comment]
Thanks for your reply, keeganwitt. yes, i'm using Gradle docker plugin. so, it is issue with  Gradle docker plugin? I mean, do i need to upgrade/update Gradle docker plugin for Spring boot 2.0.0.RELEASE?

**Comment by keeganwitt** [comment]
Yes, that's my understanding.  A couple folks in the comments said using Docker Gradle 3.2.5 fixed the issue for them, so I'd give that a try.

**Comment by batarayappa** [comment]
Thanks,Keegan Witt. It is working fine now.
