### ISSUE TITLE
compileGroovy fails inside container

### ISSUE THREAD

**Issue by kleini** [keeganwitt/docker-gradle#79]
Happens with 4.10.x and 5.0.0 version. Something confuses the homedir and therefore the ivy pattern in Grape:

<pre>
12:35:11     Local Ivy config file 'jar:file:/home/****/workspace/ins_Jenkinsfiles_kubernetes-ST4GFAO45ZKQEETSAJKAWJDJSAVUTX7JW3CXRZAK6ULRFV6F2KFQ/%3F/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.11/444a64af79c540aad257e49d95050e7c189f1309/groovy-all-2.4.11.jar!/groovy/grape/defaultGrapeConfig.xml' appears corrupt - ignoring it and using default config instead
12:35:11     Error was: failed to load settings from jar:file:/home/****/workspace/ins_Jenkinsfiles_kubernetes-ST4GFAO45ZKQEETSAJKAWJDJSAVUTX7JW3CXRZAK6ULRFV6F2KFQ/%3F/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.11/444a64af79c540aad257e49d95050e7c189f1309/groovy-all-2.4.11.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
12:35:11        6.530 [id=27]	SEVERE	****.InitReactorRunner$1#onTaskFailed: Failed GrapeHack.hack
12:35:11     java.lang.IllegalArgumentException: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
12:35:11     	at org.apache.ivy.util.Checks.checkAbsolute(Checks.java:57)
12:35:11     	at org.apache.ivy.plugins.resolver.FileSystemResolver.addConfiguredIvy(FileSystemResolver.java:303)
12:35:11     Caused: java.lang.reflect.InvocationTargetException
12:35:11     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:35:11     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:35:11     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:35:11     	at java.lang.reflect.Method.invoke(Method.java:498)
12:35:11     	at org.apache.ivy.util.Configurator.endCreateChild(Configurator.java:708)
12:35:11     Caused: java.lang.IllegalArgumentException: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
12:35:11     	at org.apache.ivy.util.Configurator.endCreateChild(Configurator.java:712)
12:35:11     	at org.apache.ivy.core.settings.XmlSettingsParser.endElement(XmlSettingsParser.java:596)
12:35:11     	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
12:35:11     	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
12:35:11     	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
12:35:11     	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
12:35:11     	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
12:35:11     	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
12:35:11     	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
12:35:11     	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
12:35:11     	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
12:35:11     	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
12:35:11     	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
12:35:11     	at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
12:35:11     	at org.apache.ivy.core.settings.XmlSettingsParser.doParse(XmlSettingsParser.java:160)
12:35:11     Caused: java.text.ParseException: failed to load settings from jar:file:/home/****/workspace/ins_Jenkinsfiles_kubernetes-ST4GFAO45ZKQEETSAJKAWJDJSAVUTX7JW3CXRZAK6ULRFV6F2KFQ/%3F/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.11/444a64af79c540aad257e49d95050e7c189f1309/groovy-all-2.4.11.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
12:35:11     	at org.apache.ivy.core.settings.XmlSettingsParser.doParse(XmlSettingsParser.java:165)
12:35:11     	at org.apache.ivy.core.settings.XmlSettingsParser.parse(XmlSettingsParser.java:150)
12:35:11     	at org.apache.ivy.core.settings.IvySettings.load(IvySettings.java:417)
12:35:11     	at org.apache.ivy.core.settings.IvySettings$load.call(Unknown Source)
12:35:11     	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
12:35:11     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
12:35:11     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
12:35:11     	at groovy.grape.GrapeIvy.<init>(GrapeIvy.groovy:102)
12:35:11     	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12:35:11     	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
12:35:11     	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:35:11     	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
12:35:11     	at java.lang.Class.newInstance(Class.java:442)
12:35:11     	at groovy.grape.Grape.getInstance(Grape.java:121)
12:35:11     	at org.****ci.plugins.workflow.cps.global.GrapeHack.hack(GrapeHack.java:47)
12:35:11     Caused: java.lang.reflect.InvocationTargetException
12:35:11     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:35:11     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:35:11     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:35:11     	at java.lang.reflect.Method.invoke(Method.java:498)
12:35:11     	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
12:35:11     Caused: java.lang.Error
12:35:11     	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
12:35:11     	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
12:35:11     	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
12:35:11     	at ****.model.Jenkins$5.runTask(Jenkins.java:1069)
12:35:11     	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
12:35:11     	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
12:35:11     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:35:11     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:35:11     	at java.lang.Thread.run(Thread.java:748)
</pre>

**Comment by keeganwitt** [comment]
Hmm... This error doesn't happen when you run the same Gradle version from outside Docker?

**Comment by keeganwitt** [comment]
I'm not sure your exact scenario, but I came across [this](https://github.com/syndesisio/syndesis/issues/41), which mentioned this [fix](https://github.com/fabric8io/kubernetes-client/commit/1a0ab37f613d497a8c53b4a0c99809ee9841a332) that looked like it might be relevant.

**Comment by kleini** [comment]
This happens when using the image as Jenkins slave with the Kubernetes Plugin. The container runs then in a Kubernetes cloud remotely and has very limited data. This might cause, that no proper environment variables are configured like $HOME and so on. I think, this causes the above described problem. I will try to investigate this later in more detail and come back then. My work priorities are currently on other topics.

**Comment by keeganwitt** [comment]
Understandable.  I'm happy to help if you revisit.

**Comment by kleini** [comment]
I am working now again on this issue. In the referenced issue some speaks about an '@' character not properly encoded in some path. In my case it looks like the character '?' causes these issues. Maybe even the '?' character is not the original character any more as some byte to character conversion already happend and the charset was not able to convert the character.
In my case the path looks like the following:

    15:57:46  Generating /home/jenkins/workspace/kins_pipeline-library_kubernetes/?/.gradle/caches/5.4/generated-gradle-jars/gradle-api-5.4.jar
    15:58:50  > Task :compileGroovy
    15:58:50  Local Ivy config file 'jar:file:/home/jenkins/workspace/kins_pipeline-library_kubernetes/%3F/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.11/444a64af79c540aad257e49d95050e7c189f1309/groovy-all-2.4.11.jar!/groovy/grape/defaultGrapeConfig.xml' appears corrupt - ignoring it and using default config instead
    15:58:50  Error was: failed to load settings from jar:file:/home/jenkins/workspace/kins_pipeline-library_kubernetes/%3F/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.11/444a64af79c540aad257e49d95050e7c189f1309/groovy-all-2.4.11.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml

Somewhere this question mark sneaks into the executing path of gradle and makes problems.

**Comment by kleini** [comment]
The issue seems to be cause by the system properties inside the container:

    16:22:31  -- listing properties --
    16:22:31  java.runtime.name=OpenJDK Runtime Environment
    16:22:31  sun.boot.library.path=/usr/lib/jvm/java-1.8-openjdk/jre/lib...
    16:22:31  java.vm.version=25.201-b08
    16:22:31  java.vm.vendor=Oracle Corporation
    16:22:31  java.vendor.url=http://java.oracle.com/
    16:22:31  path.separator=:
    16:22:31  java.vm.name=OpenJDK 64-Bit Server VM
    16:22:31  file.encoding.pkg=sun.io
    16:22:31  user.country=US
    16:22:31  sun.java.launcher=SUN_STANDARD
    16:22:31  sun.os.patch.level=unknown
    16:22:31  java.vm.specification.name=Java Virtual Machine Specification
    16:22:31  user.dir=/home/jenkins/workspace/kins_pipeline...
    16:22:31  java.runtime.version=1.8.0_201-b08
    16:22:31  java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
    16:22:31  java.endorsed.dirs=/usr/lib/jvm/java-1.8-openjdk/jre/lib...
    16:22:31  os.arch=amd64
    16:22:31  java.io.tmpdir=/tmp
    16:22:31  line.separator=
    16:22:31  
    16:22:31  org.gradle.appname=gradle
    16:22:31  java.vm.specification.vendor=Oracle Corporation
    16:22:31  user.variant=
    16:22:31  os.name=Linux
    16:22:31  sun.jnu.encoding=UTF-8
    16:22:31  java.library.path=/usr/lib/jvm/java-1.8-openjdk/jre/lib...
    16:22:31  java.specification.name=Java Platform API Specification
    16:22:31  java.class.version=52.0
    16:22:31  sun.management.compiler=HotSpot 64-Bit Tiered Compilers
    16:22:31  os.version=4.11.6-201.fc25.x86_64
    16:22:31  library.jansi.path=/home/jenkins/workspace/kins_pipeline...
    16:22:31  user.home=/home/jenkins/workspace/kins_pipeline...
    16:22:31  user.timezone=
    16:22:31  java.awt.printerjob=sun.print.PSPrinterJob
    16:22:31  file.encoding=UTF-8
    16:22:31  java.specification.version=1.8
    16:22:31  user.name=?
    16:22:31  java.class.path=/opt/gradle/lib/gradle-launcher-5.4.jar
    16:22:31  java.vm.specification.version=1.8
    16:22:31  sun.arch.data.model=64
    16:22:31  java.home=/usr/lib/jvm/java-1.8-openjdk/jre
    16:22:31  sun.java.command=org.gradle.launcher.daemon.bootstrap....
    16:22:31  java.specification.vendor=Oracle Corporation
    16:22:31  user.language=en
    16:22:31  awt.toolkit=sun.awt.X11.XToolkit
    16:22:31  java.vm.info=mixed mode
    16:22:31  java.version=1.8.0_201
    16:22:31  java.ext.dirs=/usr/lib/jvm/java-1.8-openjdk/jre/lib...
    16:22:31  sun.boot.class.path=/usr/lib/jvm/java-1.8-openjdk/jre/lib...
    16:22:31  java.vendor=Oracle Corporation
    16:22:31  file.separator=/
    16:22:31  java.vendor.url.bug=http://bugreport.sun.com/bugreport/
    16:22:31  sun.cpu.endian=little
    16:22:31  sun.io.unicode.encoding=UnicodeLittle
    16:22:31  sun.cpu.isalist=

See the user.name property, which is filled with a question mark and that is used as part of a lot of path for gradle. I replaced now everything during startup of Gradle with some useful text. Gradle still uses the question mark for its gradle.user.home.

**Comment by keeganwitt** [comment]
Which image are you using please?

**Comment by kleini** [comment]
gradle:5.4-alpine
But I can reproduce this with all actual 5.x images. The main problem is, that ${user.home} is not properly resolved inside the OpenJDK. I will try to debug this further. Would be good to know, how OpenJDK resolves this variable.

**Comment by keeganwitt** [comment]
What prints if you change the command to `whoami`?

**Comment by kleini** [comment]
14:50:30  + whoami
    14:50:30  whoami: unknown uid 10000

This is due to how Jenkins run kubernetes Pods for slaves. Within the JNLP jenkins slave uid 10000 is used and I need to use the same uid in the gradle container otherwise follow up operations on the JNLP slave fail if files are written with a root uid.

**Comment by kleini** [comment]
Okay, I just noticed, that the UID of the user in the jenkins/jnlp-slave was changed to 1000. The same UID is used by default in the gradle image. I will try to solve the issue by fetching latest images and using UID 1000.

**Comment by kleini** [comment]
And it works. Thanks for providing the hint, that helped solving the issue.

**Comment by keeganwitt** [comment]
Glad to hear it.  Apparently, Java puts a question mark anytime the call fails ([JDK-8193433](https://bugs.openjdk.java.net/browse/JDK-8193433)).  In this case because that UID doesn't exist.

**Comment by sparrowt** [comment]
I'm not using `docker-gradle` but this issue helped me a bunch - in my case I was doing the following:
```groovy
docker.image("amazoncorretto:17").inside {
    sh './gradlew check --stacktrace'
}
```
which jenkins silently turns into a `docker run` command that simplifies down to essentially:
```
docker run -it -u 1000:1000 -w /workspace -v workspace_on_host:/workspace:rw,z amazoncorretto:17
```
and then it runs gradle inside there and I was hitting errors like this:
```
SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed GrapeHack.hack
java.lang.IllegalArgumentException: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
	at org.apache.ivy.util.Checks.checkAbsolute(Checks.java:57)
...
Caused: java.text.ParseException: failed to load settings from jar:file:/home/ec2-user/jenkins/workspace/DSL_Test_PR-325/%3f/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.21/8e4f4c30dbb9123fbf703f256cd721bbac5c902a/groovy-all-2.4.21.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
	at org.apache.ivy.core.settings.XmlSettingsParser.doParse(XmlSettingsParser.java:160)

...
```

As hinted at by this thread, the issue is that UID 1000 doesn't exist within the amazoncorretto container and thus `user.home` returns `?` which confuses ivy.

To solve this I simply created a Dockerfile which creates that user on top of amazoncorretto as follows:
```Dockerfile
FROM amazoncorretto:17

RUN yum -y install shadow-utils \
    && groupadd -g 1000 foobar \
    && useradd -m -u 1000 -g 1000 -r foobar \
    && yum -y remove shadow-utils \
    && yum -y autoremove \
    && yum -y clean all
```
