### ISSUE TITLE
Cannot use nodejs plugin with Gradle

### ISSUE THREAD

**Issue by amimas** [keeganwitt/docker-gradle#88]
I use NodeJS plugin for one of my projects.

https://github.com/srs/gradle-node-plugin

When I try to use the `gradle:5.2-jre8-alpine` image, Gradle fails with the following error. It seems Gradle didn't even download nodejs in order to be executed:

```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :website:assemble UP-TO-DATE
> Task :website:nodeSetup UP-TO-DATE

FAILURE: > Task :website:yarnSetup FAILED
Build failed with an exception.

* What went wrong:
Execution failed for task ':website:yarnSetup'.
> A problem occurred starting process 'command '/home/gradle/project/website/.gradle/nodejs/node-v10.14.2-linux-x64/bin/node''

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

I then tried `gradle:5.2-jre8` image but this time I got a little bit more useful info in the stacktrace:

```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :website:assemble UP-TO-DATE
> Task :website:nodeSetup UP-TO-DATE

> Task :website:yarnSetup
/home/gradle/project/website/.gradle/yarn/yarn-v1.12.3/bin/yarn -> /home/gradle/project/website/.gradle/yarn/yarn-v1.12.3/lib/node_modules/yarn/bin/yarn.js
/home/gradle/project/website/.gradle/yarn/yarn-v1.12.3/bin/yarnpkg -> /home/gradle/project/website/.gradle/yarn/yarn-v1.12.3/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.12.3
updated 1 package in 2.533s

> Task :website:yarn_install
yarn install v1.12.3
warning package.json: No license field
warning No license field[1/4] Resolving packages...
[2/4] Fetching packages...

[3/4] Linking dependencies...
warning "markdown-spellcheck > sinon-as-promised@4.0.3" has unmet peer dependency "sinon@1".
[4/4] Building fresh packages...
error /home/gradle/project/website/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /home/gradle/project/website/node_modules/gifsicle
Output:
⚠ Command failed: /home/gradle/project/website/node_modules/gifsicle/vendor/gifsicle --version
/home/gradle/project/website/node_modules/gifsicle/vendor/gifsicle: 1: /home/gradle/project/website/node_modules/gifsicle/vendor/gifsicle: Syntax error: "(" unexpected


  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found


    at Promise.all.then.arr (/home/gradle/project/website/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

> Task :website:yarn_install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':website:yarn_install'.
> Process 'command '/home/gradle/project/website/.gradle/yarn/yarn-v1.12.3/bin/yarn'' finished with non-zero exit value 1
```
I think certain library is missing from the base image and that's why node/yarn is not running.

**Comment by keeganwitt** [comment]
Do you have a small Gradlew file that I could use to reproduce the issue?

**Comment by keeganwitt** [comment]
We can experiment to figure out what all is needed by invoking gradle interactively.
```
cd <wherever-your-project-is>
docker run --rm -it -u root -v "${PWD}":/home/gradle/project -w /home/gradle/project gradle bash
apt-get update && apt-get install -y autoconf
gradle --debug <whatever-task-you-invoked>
```

**Comment by keeganwitt** [comment]
It might be a requirement of one of your Node packages (perhaps gifsicle), and not the plugin itself.  When I cloned the yarn example [here](https://github.com/srs/gradle-node-plugin/tree/master/examples/simple-yarn), I didn't get the error you got (though I did get `java.nio.file.FileSystemException: /root/project/.gradle/nodejs/node-v6.11.0-linux-x64/bin/npm: Protocol error`).

**Comment by keeganwitt** [comment]
Closing issue for now, as I don't have information to debug this further. We can re-open if you are still fighting this issue.
